route:
    repeat_interval: 30m
    group_interval: 30m
    receiver: 'rocketchat'

receivers:
    - name: 'rocketchat'
      webhook_configs:
          - send_resolved: false
            url: '${WEBHOOK_URL}'

route:
group_by: [cluster]
# If an alert isn't caught by a route, send it to hipchat.
receiver: team-hipchat
routes:
# Send severity=hipchat alerts to hipchat.
- match:
severity: hipchat
receiver: team-hipchat

receivers:
- name: team-hipchat
hipchat_configs:
- room_id: 3372146
auth_token: <your-token>
