global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    monitor: 'my-monitor'
rule_files:
  - 'alert.rules'
scrape_configs:
  - job_name: 'prometheus'
  - job_name: 'cAdvisor'
  static_configs:
      - targets: ['${TARGET_HOST}:9090']
      - job_name: 'node-exporter'
  static_configs:
      - targets: ['node-exporter:9100']
  static_configs:
      - targets: ['${TARGET_HOST}:8080']
